#
#
#
#
#
# PRODUCTION
#
#
#
#
#
#
version: '2'
services:
    # cms
    cms:
        build: ./nginx
        volumes:
            - ../:/var/www/html
        networks:
            - fsdocker_appnet
        environment:
            - VIRTUAL_HOST=cms.lukasoppermann.de
            - VIRTUAL_PROTO=https
            - VIRTUAL_PORT=443
    # php
    cmsphp:
        image: shippingdocker/php:latest
        container_name: cmsphp
        volumes:
            - ../:/var/www/html
        # volumes_from:
        #     - cms
        networks:
            - fsdocker_appnet
    # session & cache
    cmsredis:
        container_name: cmsredis
        image: redis:alpine
        networks:
            - fsdocker_appnet
    # mysql db
    cmsdb:
        image: mysql:latest
        container_name: cmsdb
        ports:
            - "3302:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cmsdb
            MYSQL_USER: root
            MYSQL_PASSWORD: root
        volumes:
            - cmsdata:/var/lib/mysql
        networks:
            - fsdocker_appnet
# used for interal communication within docker
networks:
    fsdocker_appnet:
        external: true
# used to store and persist data
volumes:
    cmsdata:
        driver: "local"
